build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
    tests: true
filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true

coding_style:
  php: {  }

tools:
  external_code_coverage:
    timeout: 600
    runs: 3
